### ISSUE TITLE
How to Replace Perceptive API？

### ISSUE THREAD

**Issue by hacker-jerry** [thu-ml/MMTrustEval#1]
Hi author, due to the well-known network problems, China can not use google's Perceptive API, is there a simpler way to replace it?Thanks for your help!

**Comment by zycheiheihei** [comment]
Thanks for your attention to our work. PerspectiveAPI is widely used in works studying LLM safety alignment. If it's not available, Moderation API can be used for rating then. The difference should be acceptable based on our experience.
