### ISSUE TITLE
[BUG] LLava-RLHF run with BFloat16 failed

### ISSUE THREAD

**Issue by hxhcreate** [thu-ml/MMTrustEval#3]
In your implemetation at `llava_rlhf_chat.py`, you set dtype and compute type ad `torch.BFloat16` which failed with 

> mat1 and mat2 must have the same dtype but got Half and BFloat16

change it to `torch.float16` solve this problem

**Comment by zycheiheihei** [comment]
Thanks for pointing out. We have fixed this.
