### ISSUE TITLE
The channel to access the data seems to be closed

### ISSUE THREAD

**Issue by zhiyugege** [thu-ml/MMTrustEval#5]
![微信图片_20240828133736](https://github.com/user-attachments/assets/73aa8cfe-da0d-4011-8964-6462502e2c49)

**Comment by Aries-iai** [comment]
Thanks for your feedback ! We have fixed the issue, and you can continue to fill out this form.

**Comment by zycheiheihei** [comment]
We have released our data on huggingface, which will be more convenient for you to get data. We are closing this issue.
